<?php
/**
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Amasty\Xsearch\ViewModel\Slider $viewModel
 * @var \Magento\Framework\Escaper $escaper
 */

$viewModel = $block->getViewModel();
?>

<?php if ($viewModel->isCanRender()): ?>
    <div class="amsearch-slider-wrap">
        <div class="amasty-xsearch-block-header">
            <?= $escaper->escapeHtml($viewModel->getSliderTitle()) ?>
        </div>
        <?php /** @var \Magento\Catalog\Model\Product $product * */ ?>
        <div class="amsearch-slider-block"
             data-amsearch-js="slider-block">
            <?php foreach ($viewModel->getProducts() as $product): ?>
                <div class="amsearch-item product-item"
                     data-amsearch-js="product-item"
                     data-search-block-type="product"
                     data-click-url="<?= $escaper->escapeUrl($product->getProductUrl()) ?>">
                    <div class="amsearch-autocomplete-image">
                        <?= /* @noEscape */ $viewModel->getImageHtml($product) ?>
                    </div>

                    <div class="information-container">
                        <div class="product details product-item-details">
                            <a class="product-item-link"
                               href="<?= $escaper->escapeUrl($product->getProductUrl()) ?>"
                               title="<?= $escaper->escapeHtml($product->getName()) ?>">
                                <?= $escaper->escapeHtml($product->getName()) ?>
                            </a>
                            <?= /* @noEscape */ $viewModel->getReviewsHtml($product) ?>
                        </div>
                        <div class="amsearch-wrapper-inner">
                            <?= /* @noEscape */ $viewModel->getProductPriceHtml($product) ?>
                            <div class="product actions product-item-actions"
                                 item-actions="1"
                                 data-amsearch-js="item-actions">
                                <div class="actions-primary">
                                    <?php if ($product->isSalable()): ?>
                                        <form id="<?= 'amasty-xsearch-product-' . (int)$product->getId() ?>"
                                              data-role="tocart-form"
                                              action="<?= $escaper->escapeUrl($viewModel->getAddToCartUrl($product)) ?>"
                                              method="post"
                                              data-amsearch-js="add-to-cart-form"
                                        >
                                            <input type="hidden" name="product"
                                                   value="<?= (int)$product->getId() ?>">
                                            <?php if ($viewModel->isRedirectToCart()): ?>
                                                <input type="hidden" name="return_url"
                                                       value="<?= $escaper->escapeUrl($viewModel->getAddToCartPostParams($product)['data']['return_url']) ?>">
                                            <?php endif; ?>
                                            <input type="hidden"
                                                   name="uenc"
                                                   value="<?= $escaper->escapeHtml($viewModel->getAddToCartPostParams($product)['data']['uenc']) ?>">
                                            <input name="form_key"
                                                   type="hidden"
                                                   value="<?= $escaper->escapeHtml($viewModel->getFormKey()) ?>"/>
                                            <button type="submit"
                                                    title="<?= $escaper->escapeHtml(__('Add to Cart')) ?>"
                                                    class="action tocart primary">
                                                <span><?= $escaper->escapeHtml(__('Add to Cart')) ?></span>
                                            </button>
                                        </form>
                                    <?php else: ?>
                                        <?php if ($product->getIsSalable()): ?>
                                            <div class="stock available">
                                                <span><?= $escaper->escapeHtml(__('In stock')) ?></span>
                                            </div>
                                        <?php else: ?>
                                            <div class="stock unavailable">
                                                <span><?= $escaper->escapeHtml(__('Out of stock')) ?></span>
                                            </div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>

                                <div data-role="add-to-links" class="actions-secondary">
                                    <?php if ($viewModel->isWishlistAllowed()): ?>
                                        <a href="#"
                                           class="action towishlist"
                                           title="<?= $escaper->escapeHtml(__('Add to Wish List')) ?>"
                                           aria-label="<?= $escaper->escapeHtml(__('Add to Wish List')) ?>"
                                           data-post='<?= $escaper->escapeHtml($viewModel->getAddToWishlistPostParams($product)); ?>'
                                           data-action="add-to-wishlist"
                                           role="button">
                                        </a>
                                    <?php endif; ?>

                                    <a href="#"
                                       class="action tocompare"
                                       title="<?= $escaper->escapeHtml(__('Add to Compare')) ?>"
                                       aria-label="<?= $escaper->escapeHtml(__('Add to Compare')) ?>"
                                       data-post='<?= $escaper->escapeHtml($viewModel->getAddToCompareParams($product)) ?>'
                                       role="button">
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif; ?>
